workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

stages:
  - build
  - test
  - package
  - push
  - deploy

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository" # Cache Maven dependencies

cache:
  paths:
    - .m2/repository/

compile-java:
  stage: build
  image: maven:3.9.12-eclipse-temurin-25
  script:
    - echo "Building Java project with Maven..."
    - mvn compile

unit-test:
  stage: test
  image: maven:3.9.12-eclipse-temurin-25
  script:
    - echo "Running tests..."
    - mvn test

package-jar:
  stage: package
  image: maven:3.9.12-eclipse-temurin-25
  script:
    - echo "Packaging application..."
    - mvn package -DskipTests=true
  artifacts:
    paths:
      - target/*.jar

push-to-ecr:
  stage: push
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
  services:
    - docker:28-dind
  variables:
    DOCKER_HOST: tcp://docker:2375/
  id_tokens:
    GITLAB_OIDC_TOKEN:
      aud: sts.amazonaws.com
  script:
    - aws --version
    - docker version
    - docker build -t $AWS_ECR/beginner349application .
    - |
      echo "${MY_OIDC_TOKEN}" > /tmp/web_identity_token
      export AWS_WEB_IDENTITY_TOKEN_FILE=/tmp/web_identity_token      
      export AWS_ROLE_ARN=${AWS_ROLE_ARN}
      export AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION} # Ensure region is set
    - aws ecr get-login-password | docker login --username AWS --password-stdin $AWS_ECR
    - docker push $AWS_ECR/beginner349application
  dependencies:
    - package-jar

deploy-to-ecs:
  stage: deploy
  image:
    name: amazon/aws-cli:2.31.13
    entrypoint: [""]
  id_tokens:
    GITLAB_OIDC_TOKEN:
      aud: sts.amazonaws.com
  script:
    - aws --version
    - |
      echo "${MY_OIDC_TOKEN}" > /tmp/web_identity_token
      export AWS_WEB_IDENTITY_TOKEN_FILE=/tmp/web_identity_token      
      export AWS_ROLE_ARN=${AWS_ROLE_ARN}
      export AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION} # Ensure region is set
    - aws ecs update-service --cluster $AWS_ECS_CLUSTER --service $AWS_ECS_SERVICE --force-new-deployment
    - aws ecs wait services-stable --cluster $AWS_ECS_CLUSTER --services $AWS_ECS_SERVICE

# just to learn how to create a customer docker image and push to gitlab Container registry
.build_custom_docker_image:
  stage: .pre
  image: docker:28
  services:
    - docker:28-dind
  script:
    - docker version
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE/java21-maven-awscli -f ci-cd/Dockerfile .
    - docker image ls
    - docker push $CI_REGISTRY_IMAGE/java21-maven-awscli

.test_image:
  stage: build
  image: $CI_REGISTRY_IMAGE/java21-maven-awscli
  script:
    - mvn --version
    - aws --version
