spring:
  application:
    name: Beginner349
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://auth.beginner349.com/realms/myrealm

# @ConfigurationPropertiesBinding example
custom-properties:
  exit-on-errors: true
  trade-start-date: 16-10-2021

