spring:
  application:
    name: Beginner349-app
  threads:
    virtual:
      enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${JWT_ISSUER_URI:http://localhost:8081/realms/myrealm}

management:
  tracing:
    sampling:
      probability: 1.0
  otlp:
    metrics:
      export:
        url: ${OTLP_METRICS_ENDPOINT:http://localhost:4318/v1/metrics}
  opentelemetry:
    tracing:
      export:
        otlp:
          endpoint: ${OTLP_TRACES_ENDPOINT:http://localhost:4318/v1/traces}
    logging:
      export:
        otlp:
          endpoint: ${OTLP_LOGS_ENDPOINT:http://localhost:4318/v1/logs}

# @ConfigurationPropertiesBinding example
custom-properties:
  exit-on-errors: true
  trade-start-date: 16-10-2021
