spring:
  application:
    name: Beginner349Application
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://auth.beginner349.com/realms/myrealm

# @ConfigurationPropertiesBinding example
app:
  exit-on-errors: true
  trade-start-date: 16-10-2021

